export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST"
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS"
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE"

export const POST_ITEM_REQUEST = "POST_ITEM_REQUEST"
export const POST_ITEM_SUCCESS = "POST_ITEM_SUCCESS"
export const POST_ITEM_FAILURE = "POST_ITEM_FAILURE"
